[project]
name = "autou-challenge-e2e"
version = "0.1.0"
description = ""
requires-python = ">=3.14"
dependencies = [
  "python-dotenv>=1.2.2",
  "robotframework>=7.4.2",
  "robotframework-requests>=0.9.7",
  "robotframework-robocop>=8.2.3",
  "robotframework-playwright>=0.1.0",
  "robotframework-browser>=19.12.5",
]

[tool.robotcode]
python_path = ["."]

[tool.robot]
paths = ["test"]
